// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASOUxAy33A_2KKZKACXgp60HRuC3hLLCo',
    appId: '1:967224513446:web:8b1fd66dc9a1272c58f567',
    messagingSenderId: '967224513446',
    projectId: 'fir-bookmark-5253f',
    authDomain: 'fir-bookmark-5253f.firebaseapp.com',
    storageBucket: 'fir-bookmark-5253f.appspot.com',
    measurementId: 'G-7LPH1Z4EDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtpT3el41jkxYSk595LwSettLGisqC80s',
    appId: '1:967224513446:android:40d9f3bd0e67e1e958f567',
    messagingSenderId: '967224513446',
    projectId: 'fir-bookmark-5253f',
    storageBucket: 'fir-bookmark-5253f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQpPQOmmnxzqdfAC2eYY5nprgufueJCAY',
    appId: '1:967224513446:ios:22a8b8e25ae18a7c58f567',
    messagingSenderId: '967224513446',
    projectId: 'fir-bookmark-5253f',
    storageBucket: 'fir-bookmark-5253f.appspot.com',
    iosBundleId: 'com.example.firebaseBookmark',
  );
}
